name: huggingface
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - anyio=4.2.0
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=2.4.1
  - async-lru=2.0.4
  - attrs=23.2.0
  - babel=2.14.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.2
  - blas=1.0
  - bleach=6.1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.11.17
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.16.0
  - cffi=1.16.0
  - cyrus-sasl=2.1.28
  - dbus=1.13.18
  - decorator=5.1.1
  - defusedxml=0.7.1
  - eigen=3.4.0
  - entrypoints=0.4
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - expat=2.5.0
  - ffmpeg=4.2.2
  - fontconfig=2.14.1
  - fqdn=1.5.1
  - freetype=2.10.4
  - giflib=5.2.1
  - glib=2.69.1
  - gmp=6.2.1
  - gnutls=3.6.13
  - graphite2=1.3.14
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - harfbuzz=4.3.0
  - hdf5=1.12.1
  - icu=58.2
  - importlib_metadata=7.0.1
  - importlib_resources=6.1.1
  - ipykernel=5.5.5
  - ipython=8.12.0
  - ipython_genutils=0.2.0
  - isoduration=20.11.0
  - jedi=0.19.1
  - jpeg=9e
  - json5=0.9.14
  - jsonpointer=2.4
  - jsonschema=4.20.0
  - jsonschema-specifications=2023.12.1
  - jsonschema-with-format-nongpl=4.20.0
  - jupyter-lsp=2.2.1
  - jupyter_client=8.6.0
  - jupyter_core=5.7.1
  - jupyter_events=0.9.0
  - jupyter_server=2.12.4
  - jupyter_server_terminals=0.5.1
  - jupyterlab=4.0.10
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.25.2
  - krb5=1.20.1
  - lame=3.100
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcups=2.4.2
  - libcurl=8.4.0
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libgomp=11.2.0
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libnghttp2=1.57.0
  - libopenblas=0.3.20
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=12.15
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.5.1
  - libuuid=1.41.5
  - libvpx=1.7.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.10.4
  - libxslt=1.1.37
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib-inline=0.1.6
  - mistune=3.0.2
  - mysql=5.7.24
  - nbclient=0.8.0
  - nbconvert-core=7.14.1
  - nbformat=5.9.2
  - ncurses=6.4
  - nettle=3.6
  - notebook-shim=0.2.3
  - opencv=4.6.0
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=3.0.12
  - overrides=7.4.0
  - packaging=23.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.2.1
  - pixman=0.40.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.1.0
  - prometheus_client=0.19.0
  - prompt-toolkit=3.0.42
  - prompt_toolkit=3.0.42
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.17.2
  - pysocks=1.7.1
  - python=3.9.18
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.19.1
  - python-json-logger=2.0.7
  - python_abi=3.9
  - pytz=2023.3.post1
  - pyzmq=25.1.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - readline=8.2
  - referencing=0.32.1
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.10.6
  - send2trash=1.8.2
  - setuptools=68.0.0
  - six=1.16.0
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlite=3.41.2
  - stack_data=0.6.2
  - terminado=0.18.0
  - tinycss2=1.2.1
  - tk=8.6.12
  - tomli=2.0.1
  - tornado=6.3.3
  - traitlets=5.14.1
  - types-python-dateutil=2.8.19.20240106
  - typing_extensions=4.9.0
  - typing_utils=0.1.0
  - tzdata=2023c
  - uri-template=1.3.0
  - wcwidth=0.2.13
  - webcolors=1.13
  - webencodings=0.5.1
  - websocket-client=1.7.0
  - wheel=0.41.2
  - x264=1!157.20191217
  - xz=5.4.2
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - accelerate==0.23.0
    - argcomplete==3.1.6
    - certifi==2023.7.22
    - charset-normalizer==3.3.0
    - click==8.1.7
    - diffusers==0.25.0
    - filelock==3.12.4
    - fsspec==2023.9.2
    - huggingface-hub==0.20.2
    - idna==3.4
    - importlib-metadata==6.8.0
    - iprogress==0.4
    - jinja2==3.1.2
    - mpmath==1.3.0
    - networkx==3.1
    - numpy==1.26.0
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu12==8.9.2.26
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-nccl-cu12==2.18.1
    - nvidia-nvjitlink-cu12==12.2.140
    - nvidia-nvtx-cu12==12.1.105
    - pillow==10.0.1
    - pipx==1.2.1
    - psutil==5.9.5
    - pyyaml==6.0.1
    - regex==2023.10.3
    - safetensors==0.4.0
    - scipy==1.11.3
    - sympy==1.12
    - tokenizers==0.15.0
    - torch==2.1.0
    - tqdm==4.66.1
    - transformers==4.36.2
    - triton==2.1.0
    - typing-extensions==4.8.0
    - urllib3==2.0.6
    - userpath==1.9.1
