name: mmdet
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - _tflow_select=2.3.0
  - abseil-cpp=20211102.0
  - absl-py=1.3.0
  - aiohttp=3.8.3
  - aiosignal=1.2.0
  - anyio=3.6.2
  - appdirs=1.4.4
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.2.1
  - astunparse=1.6.3
  - async-timeout=4.0.2
  - attrs=22.2.0
  - babel=2.12.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.12.0
  - blas=1.0
  - bleach=6.0.0
  - blinker=1.4
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.19.0
  - ca-certificates=2023.01.10
  - cachetools=4.2.2
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - cryptography=39.0.1
  - cuda=11.6.1
  - cuda-cccl=11.6.55
  - cuda-command-line-tools=11.6.2
  - cuda-compiler=11.6.2
  - cuda-cudart=11.6.55
  - cuda-cudart-dev=11.6.55
  - cuda-cuobjdump=11.6.124
  - cuda-cupti=11.6.124
  - cuda-cuxxfilt=11.6.124
  - cuda-driver-dev=11.6.55
  - cuda-gdb=12.1.55
  - cuda-libraries=11.6.1
  - cuda-libraries-dev=11.6.1
  - cuda-memcheck=11.8.86
  - cuda-nsight=12.1.55
  - cuda-nsight-compute=12.1.0
  - cuda-nvcc=11.6.124
  - cuda-nvdisasm=12.1.55
  - cuda-nvml-dev=11.6.55
  - cuda-nvprof=12.1.55
  - cuda-nvprune=11.6.124
  - cuda-nvrtc=11.6.124
  - cuda-nvrtc-dev=11.6.124
  - cuda-nvtx=11.6.124
  - cuda-nvvp=12.1.55
  - cuda-runtime=11.6.1
  - cuda-samples=11.6.101
  - cuda-sanitizer-api=12.1.55
  - cuda-toolkit=11.6.1
  - cuda-tools=11.6.1
  - cuda-visual-tools=11.6.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=1.2.0
  - ffmpeg=4.3
  - flatbuffers=2.0.0
  - flit-core=3.8.0
  - freetype=2.12.1
  - frozenlist=1.3.3
  - gast=0.4.0
  - gds-tools=1.6.0.25
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - google-auth=2.6.0
  - google-auth-oauthlib=0.4.4
  - google-pasta=0.2.0
  - grpc-cpp=1.46.1
  - grpcio=1.42.0
  - h5py=3.7.0
  - hdf5=1.10.6
  - icu=58.2
  - idna=3.4
  - importlib-metadata=6.1.0
  - importlib_resources=5.12.0
  - intel-openmp=2021.4.0
  - ipykernel=5.5.5
  - ipython=8.11.0
  - ipython_genutils=0.2.0
  - jedi=0.18.2
  - jinja2=3.1.2
  - jpeg=9e
  - json5=0.9.5
  - jsonschema=4.17.3
  - jupyter_client=7.0.6
  - jupyter_core=4.12.0
  - jupyter_server=1.23.6
  - jupyterlab=3.5.0
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.21.0
  - keras=2.11.0
  - keras-preprocessing=1.1.2
  - krb5=1.19.4
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libcublas=11.9.2.110
  - libcublas-dev=11.9.2.110
  - libcufft=10.7.1.112
  - libcufft-dev=10.7.1.112
  - libcufile=1.6.0.25
  - libcufile-dev=1.6.0.25
  - libcurand=10.3.2.56
  - libcurand-dev=10.3.2.56
  - libcurl=7.88.1
  - libcusolver=11.3.4.124
  - libcusparse=11.7.2.124
  - libcusparse-dev=11.7.2.124
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libev=4.33
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.2
  - libnghttp2=1.46.0
  - libnpp=11.6.3.124
  - libnpp-dev=11.6.3.124
  - libnvjpeg=11.6.2.124
  - libnvjpeg-dev=11.6.2.124
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtasn1=4.16.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib-inline=0.1.6
  - mistune=2.0.5
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - multidict=6.0.2
  - nbclassic=0.5.3
  - nbclient=0.7.2
  - nbconvert-core=7.2.9
  - nbformat=5.8.0
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - nettle=3.7.3
  - notebook=6.5.3
  - notebook-shim=0.2.2
  - nsight-compute=2023.1.0.15
  - numpy=1.23.5
  - numpy-base=1.23.5
  - oauthlib=3.2.2
  - openh264=2.1.1
  - openssl=1.1.1t
  - opt_einsum=3.3.0
  - packaging=23.0
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.0.1
  - pkgutil-resolve-name=1.3.10
  - pooch=1.4.0
  - prometheus_client=0.16.0
  - prompt-toolkit=3.0.38
  - prompt_toolkit=3.0.38
  - protobuf=3.20.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pygments=2.14.0
  - pyjwt=2.4.0
  - pyopenssl=23.0.0
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.9.16
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.3
  - python-flatbuffers=2.0
  - python_abi=3.9
  - pytorch=1.13.1
  - pytorch-cuda=11.6
  - pytorch-mutex=1.0
  - pytz=2022.7.1
  - pyzmq=19.0.2
  - re2=2022.04.01
  - readline=8.2
  - requests=2.28.1
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - send2trash=1.8.0
  - setuptools=65.6.3
  - six=1.16.0
  - snappy=1.1.9
  - sniffio=1.3.0
  - soupsieve=2.3.2.post1
  - sqlite=3.41.1
  - stack_data=0.6.2
  - tensorboard=2.11.0
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.8.1
  - tensorflow=2.11.0
  - tensorflow-base=2.11.0
  - tensorflow-estimator=2.11.0
  - termcolor=2.1.0
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.12
  - tomli=2.0.1
  - torchaudio=0.13.1
  - torchvision=0.14.1
  - tornado=6.1
  - traitlets=5.9.0
  - typing_extensions=4.4.0
  - tzdata=2022g
  - urllib3=1.26.14
  - wcwidth=0.2.6
  - webencodings=0.5.1
  - websocket-client=1.5.1
  - werkzeug=2.2.3
  - wheel=0.38.4
  - wrapt=1.14.1
  - xz=5.2.10
  - yarl=1.8.1
  - zeromq=4.3.4
  - zipp=3.15.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - addict==2.4.0
    - click==8.1.3
    - colorama==0.4.6
    - contourpy==1.0.7
    - cycler==0.11.0
    - fonttools==4.39.2
    - glob2==0.7
    - kiwisolver==1.4.4
    - markdown==3.4.2
    - markdown-it-py==2.2.0
    - matplotlib==3.7.1
    - mdurl==0.1.2
    - mmcv-full==1.7.0
    - model-index==0.1.11
    - opencv-python==4.7.0.72
    - openmim==0.3.7
    - ordered-set==4.1.0
    - pandas==1.5.3
    - pycocotools==2.0.6
    - pyparsing==3.0.9
    - pyyaml==6.0
    - rich==13.3.2
    - scipy==1.10.1
    - tabulate==0.9.0
    - terminaltables==3.1.10
    - yapf==0.32.0
